import {test,expect} from '@playwright/test';
test('host creates, publishes and shares a multilingual guide',async({page,browser})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:5001');
 await expect(page.getByRole('heading',{name:'Sua hospitalidade, sem limites.'})).toBeVisible();
 await page.screenshot({path:'/tmp/houseguide-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Nova propriedade',exact:true}).click();
 await page.getByLabel('Seu nome',{exact:true}).fill('Anfitrião Teste');
 await page.getByLabel('E-mail',{exact:true}).fill(`host-${Date.now()}@example.com`);
 await page.getByLabel('Senha',{exact:true}).fill('testpassword123');
 await page.getByLabel('Aceito os termos de serviço e li a política de privacidade.').check();
 await page.getByRole('dialog').getByRole('button',{name:'Criar conta',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Sua próxima boa-vinda começa aqui'})).toBeVisible();
 await page.getByRole('button',{name:'Nova propriedade',exact:true}).click();
 await page.getByLabel('Nome da propriedade',{exact:true}).fill('Casa Teste');
 await page.getByLabel('Cidade e país',{exact:true}).fill('Lisboa, Portugal');
 await page.getByLabel('Nome da rede Wi-Fi',{exact:true}).fill('Guest Network');
 await page.getByLabel('Mensagem de boas-vindas',{exact:true}).fill('Bem-vindo à Casa Teste');
 await page.getByLabel('Idioma do conteúdo').selectOption('en');
 await page.getByLabel('Mensagem de boas-vindas',{exact:true}).fill('Welcome to Test House');
 await page.getByLabel('Idioma do conteúdo').selectOption('pt');
 await page.route('**/api/ai/translate',async route=>{
   const body=route.request().postDataJSON();
   expect(body.source).toEqual({welcomeText:'Bem-vindo à Casa Teste'});
   await route.fulfill({json:{translations:Object.fromEntries(body.targets.map(l=>[l,{welcomeText:'AI welcome '+l}]))}});
 });
 await page.getByRole('button',{name:'Traduzir com IA',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Revisar proposta'})).toBeVisible();
 await page.getByRole('button',{name:'Aplicar ao editor'}).click();
 await page.getByLabel('Idioma do conteúdo').selectOption('en');
 await expect(page.getByLabel('Mensagem de boas-vindas',{exact:true})).toHaveValue('Welcome to Test House');
 await page.getByLabel('Idioma do conteúdo').selectOption('fr');
 await expect(page.getByLabel('Mensagem de boas-vindas',{exact:true})).toHaveValue('AI welcome fr');
 await page.getByLabel('Idioma do conteúdo').selectOption('pt');
 await page.route('**/api/ai/rules',route=>route.fulfill({json:{rules:'Cuide das plantas. Animais são bem-vindos.'}}));
 await page.getByLabel('Preferências para as regras').fill('Animais permitidos e plantas');
 await page.getByRole('button',{name:'Sugerir regras',exact:true}).click();
 await expect(page.locator('.suggested-rules')).toContainText('Animais são bem-vindos.');
 await page.getByRole('dialog').screenshot({path:'/tmp/houseguide-ai-review.png'});
 await expect(page.getByLabel('Regras da casa',{exact:true})).toHaveValue('');
 await page.getByRole('button',{name:'Aplicar ao editor'}).click();
 await expect(page.getByLabel('Regras da casa',{exact:true})).toHaveValue('Cuide das plantas. Animais são bem-vindos.');
 await page.getByLabel('Publicar guia',{exact:true}).check();
 await page.getByRole('button',{name:'Salvar alterações'}).click();
 await expect(page.getByRole('heading',{name:'Casa Teste',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'QR code',exact:true}).click();
 await expect(page.locator('.qr-image')).toBeVisible();
 const url=await page.locator('.qr-url').textContent();
 const context=await browser.newContext({viewport:{width:390,height:844}});const guest=await context.newPage();
 await guest.goto(url);
 await expect(guest.getByText('Bem-vindo à Casa Teste')).toBeVisible();
 await guest.getByLabel('Idioma da interface').selectOption('en');
 await expect(guest.getByText('Welcome to Test House')).toBeVisible();
 expect(await guest.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await guest.screenshot({path:'/tmp/houseguide-guest.png',fullPage:true});
 await page.reload();
 await expect(page.getByRole('heading',{name:'Casa Teste',exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 await page.screenshot({path:'/tmp/houseguide-mobile.png',fullPage:true,animations:'disabled'});
 expect(errors).toEqual([]);await context.close();
});
