import {test,expect} from '@playwright/test';
test('photos, account rights, public documents and explicit offline copy',async({page,browser})=>{
 const base='http://127.0.0.1:5001';
 const fixture=Buffer.from('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAHgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwB1FFFcBzBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB/9k=','base64');
 const email='product-'+Date.now()+'@example.com';
 await page.goto(base);
 const registration=await page.request.post(base+'/api/auth/register',{data:{name:'Test Product',email,password:'product-pass-123',acceptTerms:true}});
 expect(registration.ok()).toBeTruthy();
 await page.reload();await expect(page.locator('.profile')).toContainText('Test Product');
 await page.getByRole('button',{name:'Nova propriedade',exact:true}).click();
 await page.getByLabel('Nome da propriedade',{exact:true}).fill('Photo House');
 await page.getByLabel('Cidade e país',{exact:true}).fill('Paris, France');
 await page.locator('input[type=file]').setInputFiles({name:'fixture.jpg',mimeType:'image/jpeg',buffer:fixture});
 await expect(page.locator('.photo-grid img')).toHaveCount(1);
 await page.getByLabel('Mensagem de boas-vindas',{exact:true}).fill('Bem-vindo offline');
 await page.getByLabel('Publicar guia',{exact:true}).check();
 await page.getByRole('button',{name:'Salvar alterações'}).click();
 await expect(page.getByRole('heading',{name:'Photo House',exact:true})).toBeVisible();
 const properties=await (await page.request.get(base+'/api/properties')).json();const property=properties[0];
 expect(property.image).toMatch(/^\/media\//);
 const guestContext=await browser.newContext({viewport:{width:390,height:844}});const guest=await guestContext.newPage();
 await guest.goto(base+'/'+property.code);await expect(guest.getByText('Bem-vindo offline')).toBeVisible();
 await guest.getByRole('button',{name:'Guardar offline',exact:true}).click();
 await expect(guest.getByText('Guia guardado neste dispositivo.')).toBeVisible({timeout:30000});
 await guestContext.setOffline(true);await guest.reload();
 await expect(guest.getByText('Bem-vindo offline')).toBeVisible();
 await expect(guest.locator('.guest-cover img')).toBeVisible();
 expect(await guest.locator('.guest-cover img').evaluate(el=>el.complete&&el.naturalWidth>0)).toBeTruthy();
 await guest.getByRole('button',{name:'Remover cópia offline',exact:true}).click();
 await expect(guest.getByText('Cópia offline removida.')).toBeVisible();
 await guestContext.setOffline(false);await guestContext.close();
 await page.getByRole('button',{name:'Configurações',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Central de privacidade'})).toBeVisible();
 await page.getByLabel('Solicitar um direito').selectOption('correction');
 await page.getByLabel('Mensagem',{exact:true}).fill('Por favor corrigir meus dados.');
 await page.getByRole('button',{name:'Enviar solicitação',exact:true}).click();
 await expect(page.getByText('Solicitação registrada.')).toBeVisible();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar meus dados'}).click();expect((await downloadPromise).suggestedFilename()).toBe('houseguide-data.json');
 await page.goto(base+'/legal');
 await expect(page.getByRole('heading',{name:'Documentos e proteção de dados'})).toBeVisible();
 await expect(page.getByText(/Audela de donnees/).first()).toBeVisible();
 await page.getByLabel('Language').selectOption('fr');
 await expect(page.getByRole('heading',{name:'Documents du service et protection des données'})).toBeVisible();
});
